let fffiles = `
./prefix_host/bin/Rscript
./prefix_host/bin/R
./prefix_host/lib/R/bin/exec/R.bin
./prefix_host/lib/R/bin/exec/R
./prefix_host/lib/R/bin/exec/R.wasm
./prefix_host/lib/R/bin/exec/R.worker.js
./prefix_host/lib/R/bin/BATCH
./prefix_host/lib/R/bin/COMPILE
./prefix_host/lib/R/bin/LINK
./prefix_host/lib/R/bin/Rd2pdf
./prefix_host/lib/R/bin/INSTALL
./prefix_host/lib/R/bin/REMOVE
./prefix_host/lib/R/bin/Rcmd
./prefix_host/lib/R/bin/Rdconv
./prefix_host/lib/R/bin/Rdiff
./prefix_host/lib/R/bin/R
./prefix_host/lib/R/bin/Rprof
./prefix_host/lib/R/bin/Rscript.wasm
./prefix_host/lib/R/bin/Rscript
./prefix_host/lib/R/bin/Stangle
./prefix_host/lib/R/bin/build
./prefix_host/lib/R/bin/SHLIB
./prefix_host/lib/R/bin/Sweave
./prefix_host/lib/R/bin/config
./prefix_host/lib/R/bin/check
./prefix_host/lib/R/bin/javareconf
./prefix_host/lib/R/bin/mkinstalldirs
./prefix_host/lib/R/bin/libtool
./prefix_host/lib/R/bin/pager
./prefix_host/lib/R/bin/rtags
./prefix_host/lib/R/bin/libR.a
./prefix_host/lib/R/bin/libRlapack.so
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_AMS-Regular.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_AMS-Regular.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Caligraphic-Bold.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Caligraphic-Bold.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_AMS-Regular.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Typewriter-Regular.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Caligraphic-Bold.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Caligraphic-Regular.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Caligraphic-Regular.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Fraktur-Bold.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Caligraphic-Regular.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Fraktur-Bold.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Fraktur-Bold.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Fraktur-Regular.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Fraktur-Regular.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Fraktur-Regular.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-BoldItalic.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-BoldItalic.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-Bold.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-Bold.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-Italic.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-Italic.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-BoldItalic.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-Italic.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-Regular.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Math-BoldItalic.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-Regular.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-Regular.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Main-Bold.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Math-BoldItalic.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Math-Italic.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Math-BoldItalic.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Math-Italic.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Math-Italic.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_SansSerif-Bold.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_SansSerif-Bold.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_SansSerif-Bold.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_SansSerif-Italic.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_SansSerif-Italic.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_SansSerif-Regular.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_SansSerif-Italic.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Script-Regular.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_SansSerif-Regular.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Script-Regular.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Script-Regular.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size1-Regular.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_SansSerif-Regular.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size1-Regular.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size2-Regular.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size1-Regular.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size2-Regular.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size3-Regular.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size3-Regular.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size3-Regular.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size2-Regular.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size4-Regular.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size4-Regular.woff
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Size4-Regular.woff2
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Typewriter-Regular.ttf
./prefix_host/lib/R/doc/html/katex/fonts/KaTeX_Typewriter-Regular.woff
./prefix_host/lib/R/doc/html/katex/LICENSE
./prefix_host/lib/R/doc/html/katex/README.md
./prefix_host/lib/R/doc/html/katex/katex.css
./prefix_host/lib/R/doc/html/katex/katex.js
./prefix_host/lib/R/doc/html/NEWS.3.html
./prefix_host/lib/R/doc/html/R.css
./prefix_host/lib/R/doc/html/NEWS.2.html
./prefix_host/lib/R/doc/html/NEWS.html
./prefix_host/lib/R/doc/html/R-nav.css
./prefix_host/lib/R/doc/html/Rlogo.svg
./prefix_host/lib/R/doc/html/about.html
./prefix_host/lib/R/doc/html/katex-config.js
./prefix_host/lib/R/doc/html/packages-head-utf8.html
./prefix_host/lib/R/doc/html/packages.html
./prefix_host/lib/R/doc/html/prism.js
./prefix_host/lib/R/doc/html/resources.html
./prefix_host/lib/R/doc/html/right.jpg
./prefix_host/lib/R/doc/html/prism.css
./prefix_host/lib/R/doc/html/up.jpg
./prefix_host/lib/R/doc/html/SearchOn.html
./prefix_host/lib/R/doc/html/Search.html
./prefix_host/lib/R/doc/html/Rlogo.pdf
./prefix_host/lib/R/doc/html/index.html
./prefix_host/lib/R/doc/html/favicon.ico
./prefix_host/lib/R/doc/html/katex-check.js
./prefix_host/lib/R/doc/html/left.jpg
./prefix_host/lib/R/doc/html/logo.jpg
./prefix_host/lib/R/doc/html/mathjax-config.js
./prefix_host/lib/R/doc/html/orcid.svg
./prefix_host/lib/R/doc/manual/images/ecdf.png
./prefix_host/lib/R/doc/manual/images/QQ.png
./prefix_host/lib/R/doc/manual/images/fig11.png
./prefix_host/lib/R/doc/manual/images/fig12.png
./prefix_host/lib/R/doc/manual/images/hist.png
./prefix_host/lib/R/doc/manual/images/ice.png
./prefix_host/lib/R/doc/manual/R-FAQ.html
./prefix_host/lib/R/doc/manual/R-admin.html
./prefix_host/lib/R/doc/manual/R-data.html
./prefix_host/lib/R/doc/manual/R-exts.html
./prefix_host/lib/R/doc/manual/R-intro.html
./prefix_host/lib/R/doc/manual/R-ints.html
./prefix_host/lib/R/doc/manual/R-lang.html
./prefix_host/lib/R/doc/BioC_mirrors.csv
./prefix_host/lib/R/doc/AUTHORS
./prefix_host/lib/R/doc/COPYING
./prefix_host/lib/R/doc/FAQ
./prefix_host/lib/R/doc/KEYWORDS
./prefix_host/lib/R/doc/CRAN_mirrors.csv
./prefix_host/lib/R/doc/COPYRIGHTS
./prefix_host/lib/R/doc/KEYWORDS.db
./prefix_host/lib/R/doc/NEWS.0
./prefix_host/lib/R/doc/NEWS
./prefix_host/lib/R/doc/NEWS.1
./prefix_host/lib/R/doc/NEWS.2
./prefix_host/lib/R/doc/NEWS.2.rds
./prefix_host/lib/R/doc/NEWS.3
./prefix_host/lib/R/doc/NEWS.3.rds
./prefix_host/lib/R/doc/NEWS.pdf
./prefix_host/lib/R/doc/NEWS.rds
./prefix_host/lib/R/doc/THANKS
./prefix_host/lib/R/doc/RESOURCES
./prefix_host/lib/R/etc/Makeconf
./prefix_host/lib/R/etc/Renviron
./prefix_host/lib/R/etc/javaconf
./prefix_host/lib/R/etc/repositories
./prefix_host/lib/R/etc/ldpaths
./prefix_host/lib/R/include/R_ext/Altrep.h
./prefix_host/lib/R/include/R_ext/Applic.h
./prefix_host/lib/R/include/R_ext/Arith.h
./prefix_host/lib/R/include/R_ext/BLAS.h
./prefix_host/lib/R/include/R_ext/Boolean.h
./prefix_host/lib/R/include/R_ext/Callbacks.h
./prefix_host/lib/R/include/R_ext/Complex.h
./prefix_host/lib/R/include/R_ext/Connections.h
./prefix_host/lib/R/include/R_ext/Constants.h
./prefix_host/lib/R/include/R_ext/Error.h
./prefix_host/lib/R/include/R_ext/GraphicsDevice.h
./prefix_host/lib/R/include/R_ext/GetX11Image.h
./prefix_host/lib/R/include/R_ext/GraphicsEngine.h
./prefix_host/lib/R/include/R_ext/Itermacros.h
./prefix_host/lib/R/include/R_ext/Lapack.h
./prefix_host/lib/R/include/R_ext/Linpack.h
./prefix_host/lib/R/include/R_ext/MathThreads.h
./prefix_host/lib/R/include/R_ext/Memory.h
./prefix_host/lib/R/include/R_ext/Print.h
./prefix_host/lib/R/include/R_ext/Parse.h
./prefix_host/lib/R/include/R_ext/PrtUtil.h
./prefix_host/lib/R/include/R_ext/QuartzDevice.h
./prefix_host/lib/R/include/R_ext/RS.h
./prefix_host/lib/R/include/R_ext/RStartup.h
./prefix_host/lib/R/include/R_ext/Rallocators.h
./prefix_host/lib/R/include/R_ext/Random.h
./prefix_host/lib/R/include/R_ext/Rdynload.h
./prefix_host/lib/R/include/R_ext/Riconv.h
./prefix_host/lib/R/include/R_ext/Utils.h
./prefix_host/lib/R/include/R_ext/Visibility.h
./prefix_host/lib/R/include/R_ext/libextern.h
./prefix_host/lib/R/include/R_ext/eventloop.h
./prefix_host/lib/R/include/R_ext/stats_package.h
./prefix_host/lib/R/include/R_ext/stats_stubs.h
./prefix_host/lib/R/include/R.h
./prefix_host/lib/R/include/Rconfig.h
./prefix_host/lib/R/include/Rembedded.h
./prefix_host/lib/R/include/Rinterface.h
./prefix_host/lib/R/include/Rdefines.h
./prefix_host/lib/R/include/Rinternals.h
./prefix_host/lib/R/include/Rmath.h
./prefix_host/lib/R/include/Rversion.h
./prefix_host/lib/R/include/libintl.h
./prefix_host/lib/R/lib/libR.a
./prefix_host/lib/R/lib/libRlapack.so
./prefix_host/lib/R/library/base/Meta/Rd.rds
./prefix_host/lib/R/library/base/Meta/demo.rds
./prefix_host/lib/R/library/base/Meta/features.rds
./prefix_host/lib/R/library/base/Meta/hsearch.rds
./prefix_host/lib/R/library/base/Meta/links.rds
./prefix_host/lib/R/library/base/Meta/package.rds
./prefix_host/lib/R/library/base/R/Rprofile
./prefix_host/lib/R/library/base/R/base
./prefix_host/lib/R/library/base/demo/error.catching.R
./prefix_host/lib/R/library/base/demo/scoping.R
./prefix_host/lib/R/library/base/demo/is.things.R
./prefix_host/lib/R/library/base/demo/recursion.R
./prefix_host/lib/R/library/base/help/AnIndex
./prefix_host/lib/R/library/base/help/aliases.rds
./prefix_host/lib/R/library/base/help/base.rdb
./prefix_host/lib/R/library/base/help/base.rdx
./prefix_host/lib/R/library/base/help/paths.rds
./prefix_host/lib/R/library/base/html/00Index.html
./prefix_host/lib/R/library/base/html/R.css
./prefix_host/lib/R/library/base/CITATION
./prefix_host/lib/R/library/base/DESCRIPTION
./prefix_host/lib/R/library/base/INDEX
./prefix_host/lib/R/library/compiler/Meta/Rd.rds
./prefix_host/lib/R/library/compiler/Meta/hsearch.rds
./prefix_host/lib/R/library/compiler/Meta/features.rds
./prefix_host/lib/R/library/compiler/Meta/nsInfo.rds
./prefix_host/lib/R/library/compiler/Meta/links.rds
./prefix_host/lib/R/library/compiler/Meta/package.rds
./prefix_host/lib/R/library/compiler/R/compiler
./prefix_host/lib/R/library/compiler/help/AnIndex
./prefix_host/lib/R/library/compiler/help/aliases.rds
./prefix_host/lib/R/library/compiler/help/compiler.rdx
./prefix_host/lib/R/library/compiler/help/compiler.rdb
./prefix_host/lib/R/library/compiler/help/paths.rds
./prefix_host/lib/R/library/compiler/html/00Index.html
./prefix_host/lib/R/library/compiler/html/R.css
./prefix_host/lib/R/library/compiler/DESCRIPTION
./prefix_host/lib/R/library/compiler/INDEX
./prefix_host/lib/R/library/compiler/NAMESPACE
./prefix_host/lib/R/library/datasets/Meta/Rd.rds
./prefix_host/lib/R/library/datasets/Meta/data.rds
./prefix_host/lib/R/library/datasets/Meta/features.rds
./prefix_host/lib/R/library/datasets/Meta/links.rds
./prefix_host/lib/R/library/datasets/Meta/hsearch.rds
./prefix_host/lib/R/library/datasets/Meta/nsInfo.rds
./prefix_host/lib/R/library/datasets/Meta/package.rds
./prefix_host/lib/R/library/datasets/data/AirPassengers.R
./prefix_host/lib/R/library/datasets/data/LakeHuron.R
./prefix_host/lib/R/library/datasets/data/BJsales.R
./prefix_host/lib/R/library/datasets/data/UKgas.R
./prefix_host/lib/R/library/datasets/data/BOD.R
./prefix_host/lib/R/library/datasets/data/ability.cov.R
./prefix_host/lib/R/library/datasets/data/CO2.rda
./prefix_host/lib/R/library/datasets/data/ChickWeight.R
./prefix_host/lib/R/library/datasets/data/DNase.R
./prefix_host/lib/R/library/datasets/data/Formaldehyde.R
./prefix_host/lib/R/library/datasets/data/HairEyeColor.R
./prefix_host/lib/R/library/datasets/data/occupationalStatus.R
./prefix_host/lib/R/library/datasets/data/precip.R
./prefix_host/lib/R/library/datasets/data/state.R
./prefix_host/lib/R/library/datasets/data/sunspot.month.R
./prefix_host/lib/R/library/datasets/data/swiss.tab
./prefix_host/lib/R/library/datasets/data/treering.R
./prefix_host/lib/R/library/datasets/data/EuStockMarkets.R
./prefix_host/lib/R/library/datasets/data/Indometh.R
./prefix_host/lib/R/library/datasets/data/Harman23.cor.R
./prefix_host/lib/R/library/datasets/data/Harman74.cor.R
./prefix_host/lib/R/library/datasets/data/InsectSprays.R
./prefix_host/lib/R/library/datasets/data/JohnsonJohnson.R
./prefix_host/lib/R/library/datasets/data/LifeCycleSavings.R
./prefix_host/lib/R/library/datasets/data/Loblolly.R
./prefix_host/lib/R/library/datasets/data/Nile.R
./prefix_host/lib/R/library/datasets/data/Orange.R
./prefix_host/lib/R/library/datasets/data/PlantGrowth.R
./prefix_host/lib/R/library/datasets/data/OrchardSprays.R
./prefix_host/lib/R/library/datasets/data/Puromycin.R
./prefix_host/lib/R/library/datasets/data/Theoph.R
./prefix_host/lib/R/library/datasets/data/Seatbelts.R
./prefix_host/lib/R/library/datasets/data/Titanic.R
./prefix_host/lib/R/library/datasets/data/ToothGrowth.R
./prefix_host/lib/R/library/datasets/data/UCBAdmissions.R
./prefix_host/lib/R/library/datasets/data/UKDriverDeaths.R
./prefix_host/lib/R/library/datasets/data/UKLungDeaths.R
./prefix_host/lib/R/library/datasets/data/USAccDeaths.R
./prefix_host/lib/R/library/datasets/data/USArrests.tab
./prefix_host/lib/R/library/datasets/data/USJudgeRatings.R
./prefix_host/lib/R/library/datasets/data/USPersonalExpenditure.R
./prefix_host/lib/R/library/datasets/data/WWWusage.R
./prefix_host/lib/R/library/datasets/data/VADeaths.R
./prefix_host/lib/R/library/datasets/data/UScitiesD.rda
./prefix_host/lib/R/library/datasets/data/WorldPhones.R
./prefix_host/lib/R/library/datasets/data/airmiles.R
./prefix_host/lib/R/library/datasets/data/airquality.tab
./prefix_host/lib/R/library/datasets/data/anscombe.R
./prefix_host/lib/R/library/datasets/data/attenu.R
./prefix_host/lib/R/library/datasets/data/attitude.R
./prefix_host/lib/R/library/datasets/data/beavers.R
./prefix_host/lib/R/library/datasets/data/austres.R
./prefix_host/lib/R/library/datasets/data/cars.R
./prefix_host/lib/R/library/datasets/data/co2.R
./prefix_host/lib/R/library/datasets/data/crimtab.rda
./prefix_host/lib/R/library/datasets/data/chickwts.R
./prefix_host/lib/R/library/datasets/data/discoveries.R
./prefix_host/lib/R/library/datasets/data/esoph.R
./prefix_host/lib/R/library/datasets/data/euro.R
./prefix_host/lib/R/library/datasets/data/eurodist.R
./prefix_host/lib/R/library/datasets/data/faithful.R
./prefix_host/lib/R/library/datasets/data/freeny.R
./prefix_host/lib/R/library/datasets/data/infert.R
./prefix_host/lib/R/library/datasets/data/iris.R
./prefix_host/lib/R/library/datasets/data/iris3.R
./prefix_host/lib/R/library/datasets/data/islands.R
./prefix_host/lib/R/library/datasets/data/lh.R
./prefix_host/lib/R/library/datasets/data/longley.R
./prefix_host/lib/R/library/datasets/data/lynx.R
./prefix_host/lib/R/library/datasets/data/morley.tab
./prefix_host/lib/R/library/datasets/data/mtcars.R
./prefix_host/lib/R/library/datasets/data/nhtemp.R
./prefix_host/lib/R/library/datasets/data/nottem.R
./prefix_host/lib/R/library/datasets/data/npk.rda
./prefix_host/lib/R/library/datasets/data/presidents.R
./prefix_host/lib/R/library/datasets/data/pressure.R
./prefix_host/lib/R/library/datasets/data/quakes.tab
./prefix_host/lib/R/library/datasets/data/randu.R
./prefix_host/lib/R/library/datasets/data/rivers.R
./prefix_host/lib/R/library/datasets/data/rock.tab
./prefix_host/lib/R/library/datasets/data/sleep.R
./prefix_host/lib/R/library/datasets/data/stackloss.R
./prefix_host/lib/R/library/datasets/data/sunspot.year.R
./prefix_host/lib/R/library/datasets/data/sunspots.R
./prefix_host/lib/R/library/datasets/data/trees.R
./prefix_host/lib/R/library/datasets/data/volcano.R
./prefix_host/lib/R/library/datasets/data/uspop.R
./prefix_host/lib/R/library/datasets/data/warpbreaks.R
./prefix_host/lib/R/library/datasets/data/women.R
./prefix_host/lib/R/library/datasets/help/AnIndex
./prefix_host/lib/R/library/datasets/help/aliases.rds
./prefix_host/lib/R/library/datasets/help/datasets.rdb
./prefix_host/lib/R/library/datasets/help/datasets.rdx
./prefix_host/lib/R/library/datasets/help/paths.rds
./prefix_host/lib/R/library/datasets/html/00Index.html
./prefix_host/lib/R/library/datasets/html/R.css
./prefix_host/lib/R/library/datasets/DESCRIPTION
./prefix_host/lib/R/library/datasets/INDEX
./prefix_host/lib/R/library/datasets/NAMESPACE
./prefix_host/lib/R/library/grDevices/Meta/Rd.rds
./prefix_host/lib/R/library/grDevices/Meta/demo.rds
./prefix_host/lib/R/library/grDevices/Meta/features.rds
./prefix_host/lib/R/library/grDevices/Meta/hsearch.rds
./prefix_host/lib/R/library/grDevices/Meta/links.rds
./prefix_host/lib/R/library/grDevices/Meta/nsInfo.rds
./prefix_host/lib/R/library/grDevices/Meta/package.rds
./prefix_host/lib/R/library/grDevices/R/grDevices
./prefix_host/lib/R/library/grDevices/afm/ArialMT-Bold.afm.gz
./prefix_host/lib/R/library/grDevices/afm/ArialMT-BoldItalic.afm.gz
./prefix_host/lib/R/library/grDevices/afm/ArialMT.afm.gz
./prefix_host/lib/R/library/grDevices/afm/ArialMT-Italic.afm.gz
./prefix_host/lib/R/library/grDevices/afm/CM_boldx_10.afm.gz
./prefix_host/lib/R/library/grDevices/afm/MustRead.html
./prefix_host/lib/R/library/grDevices/afm/NimbusMonoPS-Bold.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusRoman-Italic.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusSans-Italic.afm.gz
./prefix_host/lib/R/library/grDevices/afm/CM_italic_10.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Times-Italic.afm.gz
./prefix_host/lib/R/library/grDevices/afm/a010035l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/CM_boldx_italic_10.afm.gz
./prefix_host/lib/R/library/grDevices/afm/agd_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/agw_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/agdo____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/CM_regular_10.afm.gz
./prefix_host/lib/R/library/grDevices/afm/agwo____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/b018012l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/b018035l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/b018032l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/b018015l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/bkd_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/bkdi____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/bkl_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/cmti10.afm.gz
./prefix_host/lib/R/library/grDevices/afm/hv______.afm.gz
./prefix_host/lib/R/library/grDevices/afm/CM_symbol_10.afm.gz
./prefix_host/lib/R/library/grDevices/afm/hvb_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/hvn_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/hvnb____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/hvnbo___.afm.gz
./prefix_host/lib/R/library/grDevices/afm/hvno____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Courier-Bold.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n019004l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Courier-BoldOblique.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Courier-Oblique.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Courier.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n022004l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n022023l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/ncb_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/ncr_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/p052003l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/p052004l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/p052023l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Helvetica-Bold.afm.gz
./prefix_host/lib/R/library/grDevices/afm/pob_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/pobi____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/por_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/poi_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/sy______.afm.gz
./prefix_host/lib/R/library/grDevices/afm/s050000l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/tib_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/tibi____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/tii_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/tir_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Helvetica-BoldOblique.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Helvetica.afm.gz
./prefix_host/lib/R/library/grDevices/afm/LICENSE.LPPL
./prefix_host/lib/R/library/grDevices/afm/Helvetica-Oblique.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusMonoPS-BoldItalic.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusMonoPS-Italic.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusMonoPS-Regular.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusRoman-Bold.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusRoman-BoldItalic.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusSans-BoldItalic.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusSans-Bold.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusSans-BoldOblique.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusRoman-Regular.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusSans-Oblique.afm.gz
./prefix_host/lib/R/library/grDevices/afm/NimbusSans-Regular.afm.gz
./prefix_host/lib/R/library/grDevices/afm/README
./prefix_host/lib/R/library/grDevices/afm/StandardSymbolsPS.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Symbol.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Times-Bold.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Times-BoldItalic.afm.gz
./prefix_host/lib/R/library/grDevices/afm/Times-Roman.afm.gz
./prefix_host/lib/R/library/grDevices/afm/ZapfDingbats.afm.gz
./prefix_host/lib/R/library/grDevices/afm/a010013l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/a010015l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/a010033l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/bkli____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/c059013l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/c059016l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/c059033l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/c059036l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/cmbxti10.afm.gz
./prefix_host/lib/R/library/grDevices/afm/cob_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/cobo____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/com_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/coo_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/hvbo____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/hvo_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n019003l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n019023l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n019043l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n019024l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n019044l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n019063l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n019064l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n021004l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n021003l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n021024l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n021023l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n022003l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/n022024l.afm.gz
./prefix_host/lib/R/library/grDevices/afm/nci_____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/ncbi____.afm.gz
./prefix_host/lib/R/library/grDevices/afm/p052024l.afm.gz
./prefix_host/lib/R/library/grDevices/demo/hclColors.R
./prefix_host/lib/R/library/grDevices/demo/colors.R
./prefix_host/lib/R/library/grDevices/enc/AdobeSym.enc
./prefix_host/lib/R/library/grDevices/enc/Greek.enc
./prefix_host/lib/R/library/grDevices/enc/ISOLatin1.enc
./prefix_host/lib/R/library/grDevices/enc/PDFDoc.enc
./prefix_host/lib/R/library/grDevices/enc/AdobeStd.enc
./prefix_host/lib/R/library/grDevices/enc/CP1251.enc
./prefix_host/lib/R/library/grDevices/enc/CP1253.enc
./prefix_host/lib/R/library/grDevices/enc/CP1250.enc
./prefix_host/lib/R/library/grDevices/enc/CP1257.enc
./prefix_host/lib/R/library/grDevices/enc/Cyrillic.enc
./prefix_host/lib/R/library/grDevices/enc/ISOLatin7.enc
./prefix_host/lib/R/library/grDevices/enc/ISOLatin2.enc
./prefix_host/lib/R/library/grDevices/enc/ISOLatin9.enc
./prefix_host/lib/R/library/grDevices/enc/KOI8-U.enc
./prefix_host/lib/R/library/grDevices/enc/KOI8-R.enc
./prefix_host/lib/R/library/grDevices/enc/TeXtext.enc
./prefix_host/lib/R/library/grDevices/enc/WinAnsi.enc
./prefix_host/lib/R/library/grDevices/fonts/Montserrat/static/Montserrat-BoldItalic.ttf
./prefix_host/lib/R/library/grDevices/fonts/Montserrat/static/Montserrat-Medium.ttf
./prefix_host/lib/R/library/grDevices/fonts/Roboto/LICENSE.txt
./prefix_host/lib/R/library/grDevices/fonts/Roboto/Roboto-Medium.ttf
./prefix_host/lib/R/library/grDevices/help/AnIndex
./prefix_host/lib/R/library/grDevices/help/paths.rds
./prefix_host/lib/R/library/grDevices/help/aliases.rds
./prefix_host/lib/R/library/grDevices/help/grDevices.rdb
./prefix_host/lib/R/library/grDevices/help/grDevices.rdx
./prefix_host/lib/R/library/grDevices/html/00Index.html
./prefix_host/lib/R/library/grDevices/html/R.css
./prefix_host/lib/R/library/grDevices/icc/srgb
./prefix_host/lib/R/library/grDevices/icc/srgb.flate
./prefix_host/lib/R/library/grDevices/libs/grDevices.so
./prefix_host/lib/R/library/grDevices/DESCRIPTION
./prefix_host/lib/R/library/grDevices/INDEX
./prefix_host/lib/R/library/grDevices/NAMESPACE
./prefix_host/lib/R/library/graphics/Meta/Rd.rds
./prefix_host/lib/R/library/graphics/Meta/hsearch.rds
./prefix_host/lib/R/library/graphics/Meta/demo.rds
./prefix_host/lib/R/library/graphics/Meta/features.rds
./prefix_host/lib/R/library/graphics/Meta/links.rds
./prefix_host/lib/R/library/graphics/Meta/nsInfo.rds
./prefix_host/lib/R/library/graphics/Meta/package.rds
./prefix_host/lib/R/library/graphics/R/graphics
./prefix_host/lib/R/library/graphics/demo/Hershey.R
./prefix_host/lib/R/library/graphics/demo/Japanese.R
./prefix_host/lib/R/library/graphics/demo/image.R
./prefix_host/lib/R/library/graphics/demo/graphics.R
./prefix_host/lib/R/library/graphics/demo/persp.R
./prefix_host/lib/R/library/graphics/demo/plotmath.R
./prefix_host/lib/R/library/graphics/help/figures/mai.pdf
./prefix_host/lib/R/library/graphics/help/figures/mai.png
./prefix_host/lib/R/library/graphics/help/figures/oma.pdf
./prefix_host/lib/R/library/graphics/help/figures/oma.png
./prefix_host/lib/R/library/graphics/help/figures/pch.pdf
./prefix_host/lib/R/library/graphics/help/figures/pch.png
./prefix_host/lib/R/library/graphics/help/figures/pch.svg
./prefix_host/lib/R/library/graphics/help/AnIndex
./prefix_host/lib/R/library/graphics/help/aliases.rds
./prefix_host/lib/R/library/graphics/help/paths.rds
./prefix_host/lib/R/library/graphics/help/graphics.rdb
./prefix_host/lib/R/library/graphics/help/graphics.rdx
./prefix_host/lib/R/library/graphics/html/R.css
./prefix_host/lib/R/library/graphics/html/00Index.html
./prefix_host/lib/R/library/graphics/libs/graphics.so
./prefix_host/lib/R/library/graphics/DESCRIPTION
./prefix_host/lib/R/library/graphics/INDEX
./prefix_host/lib/R/library/graphics/NAMESPACE
./prefix_host/lib/R/library/grid/Meta/hsearch.rds
./prefix_host/lib/R/library/grid/Meta/Rd.rds
./prefix_host/lib/R/library/grid/Meta/package.rds
./prefix_host/lib/R/library/grid/Meta/features.rds
./prefix_host/lib/R/library/grid/Meta/links.rds
./prefix_host/lib/R/library/grid/Meta/nsInfo.rds
./prefix_host/lib/R/library/grid/R/grid
./prefix_host/lib/R/library/grid/doc/DivByZero.txt
./prefix_host/lib/R/library/grid/doc/frame.pdf
./prefix_host/lib/R/library/grid/doc/displaylist.pdf
./prefix_host/lib/R/library/grid/doc/grid.pdf
./prefix_host/lib/R/library/grid/doc/changes.txt
./prefix_host/lib/R/library/grid/doc/grobs.pdf
./prefix_host/lib/R/library/grid/doc/rotated.pdf
./prefix_host/lib/R/library/grid/doc/interactive.pdf
./prefix_host/lib/R/library/grid/doc/locndimn.pdf
./prefix_host/lib/R/library/grid/doc/moveline.pdf
./prefix_host/lib/R/library/grid/doc/nonfinite.pdf
./prefix_host/lib/R/library/grid/doc/plotexample.pdf
./prefix_host/lib/R/library/grid/doc/saveload.pdf
./prefix_host/lib/R/library/grid/doc/sharing.pdf
./prefix_host/lib/R/library/grid/doc/viewports.pdf
./prefix_host/lib/R/library/grid/help/AnIndex
./prefix_host/lib/R/library/grid/help/grid.rdb
./prefix_host/lib/R/library/grid/help/aliases.rds
./prefix_host/lib/R/library/grid/help/grid.rdx
./prefix_host/lib/R/library/grid/help/paths.rds
./prefix_host/lib/R/library/grid/html/00Index.html
./prefix_host/lib/R/library/grid/html/R.css
./prefix_host/lib/R/library/grid/libs/grid.so
./prefix_host/lib/R/library/grid/DESCRIPTION
./prefix_host/lib/R/library/grid/INDEX
./prefix_host/lib/R/library/grid/NAMESPACE
./prefix_host/lib/R/library/methods/Meta/Rd.rds
./prefix_host/lib/R/library/methods/Meta/features.rds
./prefix_host/lib/R/library/methods/Meta/hsearch.rds
./prefix_host/lib/R/library/methods/Meta/links.rds
./prefix_host/lib/R/library/methods/Meta/nsInfo.rds
./prefix_host/lib/R/library/methods/Meta/package.rds
./prefix_host/lib/R/library/methods/R/methods
./prefix_host/lib/R/library/methods/help/AnIndex
./prefix_host/lib/R/library/methods/help/aliases.rds
./prefix_host/lib/R/library/methods/help/methods.rdx
./prefix_host/lib/R/library/methods/help/methods.rdb
./prefix_host/lib/R/library/methods/help/paths.rds
./prefix_host/lib/R/library/methods/html/00Index.html
./prefix_host/lib/R/library/methods/html/R.css
./prefix_host/lib/R/library/methods/libs/methods.so
./prefix_host/lib/R/library/methods/DESCRIPTION
./prefix_host/lib/R/library/methods/INDEX
./prefix_host/lib/R/library/methods/NAMESPACE
./prefix_host/lib/R/library/parallel/Meta/Rd.rds
./prefix_host/lib/R/library/parallel/Meta/features.rds
./prefix_host/lib/R/library/parallel/Meta/hsearch.rds
./prefix_host/lib/R/library/parallel/Meta/nsInfo.rds
./prefix_host/lib/R/library/parallel/Meta/links.rds
./prefix_host/lib/R/library/parallel/Meta/package.rds
./prefix_host/lib/R/library/parallel/R/parallel
./prefix_host/lib/R/library/parallel/doc/parallel.pdf
./prefix_host/lib/R/library/parallel/help/aliases.rds
./prefix_host/lib/R/library/parallel/help/AnIndex
./prefix_host/lib/R/library/parallel/help/parallel.rdb
./prefix_host/lib/R/library/parallel/help/parallel.rdx
./prefix_host/lib/R/library/parallel/help/paths.rds
./prefix_host/lib/R/library/parallel/html/00Index.html
./prefix_host/lib/R/library/parallel/html/R.css
./prefix_host/lib/R/library/parallel/libs/parallel.so
./prefix_host/lib/R/library/parallel/INDEX
./prefix_host/lib/R/library/parallel/DESCRIPTION
./prefix_host/lib/R/library/parallel/NAMESPACE
./prefix_host/lib/R/library/splines/Meta/hsearch.rds
./prefix_host/lib/R/library/splines/Meta/features.rds
./prefix_host/lib/R/library/splines/Meta/Rd.rds
./prefix_host/lib/R/library/splines/Meta/nsInfo.rds
./prefix_host/lib/R/library/splines/Meta/links.rds
./prefix_host/lib/R/library/splines/Meta/package.rds
./prefix_host/lib/R/library/splines/R/splines
./prefix_host/lib/R/library/splines/help/AnIndex
./prefix_host/lib/R/library/splines/help/aliases.rds
./prefix_host/lib/R/library/splines/help/paths.rds
./prefix_host/lib/R/library/splines/help/splines.rdb
./prefix_host/lib/R/library/splines/help/splines.rdx
./prefix_host/lib/R/library/splines/html/00Index.html
./prefix_host/lib/R/library/splines/html/R.css
./prefix_host/lib/R/library/splines/libs/splines.so
./prefix_host/lib/R/library/splines/DESCRIPTION
./prefix_host/lib/R/library/splines/INDEX
./prefix_host/lib/R/library/splines/NAMESPACE
./prefix_host/lib/R/library/stats/Meta/Rd.rds
./prefix_host/lib/R/library/stats/Meta/demo.rds
./prefix_host/lib/R/library/stats/Meta/features.rds
./prefix_host/lib/R/library/stats/Meta/hsearch.rds
./prefix_host/lib/R/library/stats/Meta/links.rds
./prefix_host/lib/R/library/stats/Meta/nsInfo.rds
./prefix_host/lib/R/library/stats/Meta/package.rds
./prefix_host/lib/R/library/stats/R/stats
./prefix_host/lib/R/library/stats/demo/glm.vr.R
./prefix_host/lib/R/library/stats/demo/lm.glm.R
./prefix_host/lib/R/library/stats/demo/nlm.R
./prefix_host/lib/R/library/stats/demo/smooth.R
./prefix_host/lib/R/library/stats/help/AnIndex
./prefix_host/lib/R/library/stats/help/aliases.rds
./prefix_host/lib/R/library/stats/help/paths.rds
./prefix_host/lib/R/library/stats/help/stats.rdb
./prefix_host/lib/R/library/stats/help/stats.rdx
./prefix_host/lib/R/library/stats/html/00Index.html
./prefix_host/lib/R/library/stats/html/R.css
./prefix_host/lib/R/library/stats/libs/stats.so
./prefix_host/lib/R/library/stats/COPYRIGHTS.modreg
./prefix_host/lib/R/library/stats/DESCRIPTION
./prefix_host/lib/R/library/stats/INDEX
./prefix_host/lib/R/library/stats/NAMESPACE
./prefix_host/lib/R/library/stats/SOURCES.ts
./prefix_host/lib/R/library/stats4/Meta/Rd.rds
./prefix_host/lib/R/library/stats4/Meta/features.rds
./prefix_host/lib/R/library/stats4/Meta/hsearch.rds
./prefix_host/lib/R/library/stats4/Meta/links.rds
./prefix_host/lib/R/library/stats4/Meta/nsInfo.rds
./prefix_host/lib/R/library/stats4/Meta/package.rds
./prefix_host/lib/R/library/stats4/R/stats4
./prefix_host/lib/R/library/stats4/help/AnIndex
./prefix_host/lib/R/library/stats4/help/aliases.rds
./prefix_host/lib/R/library/stats4/help/stats4.rdb
./prefix_host/lib/R/library/stats4/help/paths.rds
./prefix_host/lib/R/library/stats4/help/stats4.rdx
./prefix_host/lib/R/library/stats4/html/00Index.html
./prefix_host/lib/R/library/stats4/html/R.css
./prefix_host/lib/R/library/stats4/DESCRIPTION
./prefix_host/lib/R/library/stats4/INDEX
./prefix_host/lib/R/library/stats4/NAMESPACE
./prefix_host/lib/R/library/tcltk/Meta/Rd.rds
./prefix_host/lib/R/library/tcltk/Meta/hsearch.rds
./prefix_host/lib/R/library/tcltk/Meta/links.rds
./prefix_host/lib/R/library/tcltk/Meta/demo.rds
./prefix_host/lib/R/library/tcltk/Meta/features.rds
./prefix_host/lib/R/library/tcltk/Meta/nsInfo.rds
./prefix_host/lib/R/library/tcltk/Meta/package.rds
./prefix_host/lib/R/library/tcltk/R/tcltk
./prefix_host/lib/R/library/tcltk/demo/tkfaq.R
./prefix_host/lib/R/library/tcltk/demo/tkdensity.R
./prefix_host/lib/R/library/tcltk/demo/tkcanvas.R
./prefix_host/lib/R/library/tcltk/demo/tkttest.R
./prefix_host/lib/R/library/tcltk/exec/Tk-frontend.R
./prefix_host/lib/R/library/tcltk/exec/console.tcl
./prefix_host/lib/R/library/tcltk/exec/hierarchy.tcl
./prefix_host/lib/R/library/tcltk/exec/pkgIndex.tcl
./prefix_host/lib/R/library/tcltk/exec/util-dump.tcl
./prefix_host/lib/R/library/tcltk/exec/progressbar.tcl
./prefix_host/lib/R/library/tcltk/exec/util-expand.tcl
./prefix_host/lib/R/library/tcltk/exec/util-number.tcl
./prefix_host/lib/R/library/tcltk/exec/util-string.tcl
./prefix_host/lib/R/library/tcltk/exec/util-tk.tcl
./prefix_host/lib/R/library/tcltk/exec/util.tcl
./prefix_host/lib/R/library/tcltk/exec/widget.tcl
./prefix_host/lib/R/library/tcltk/help/AnIndex
./prefix_host/lib/R/library/tcltk/help/aliases.rds
./prefix_host/lib/R/library/tcltk/help/paths.rds
./prefix_host/lib/R/library/tcltk/help/tcltk.rdb
./prefix_host/lib/R/library/tcltk/help/tcltk.rdx
./prefix_host/lib/R/library/tcltk/html/R.css
./prefix_host/lib/R/library/tcltk/html/00Index.html
./prefix_host/lib/R/library/tcltk/DESCRIPTION
./prefix_host/lib/R/library/tcltk/INDEX
./prefix_host/lib/R/library/tcltk/NAMESPACE
./prefix_host/lib/R/library/tools/Meta/Rd.rds
./prefix_host/lib/R/library/tools/Meta/features.rds
./prefix_host/lib/R/library/tools/Meta/hsearch.rds
./prefix_host/lib/R/library/tools/Meta/links.rds
./prefix_host/lib/R/library/tools/Meta/package.rds
./prefix_host/lib/R/library/tools/Meta/nsInfo.rds
./prefix_host/lib/R/library/tools/R/sysdata.rdx
./prefix_host/lib/R/library/tools/R/tools
./prefix_host/lib/R/library/tools/R/sysdata.rdb
./prefix_host/lib/R/library/tools/help/AnIndex
./prefix_host/lib/R/library/tools/help/aliases.rds
./prefix_host/lib/R/library/tools/help/paths.rds
./prefix_host/lib/R/library/tools/help/tools.rdb
./prefix_host/lib/R/library/tools/help/tools.rdx
./prefix_host/lib/R/library/tools/html/00Index.html
./prefix_host/lib/R/library/tools/html/R.css
./prefix_host/lib/R/library/tools/libs/tools.so
./prefix_host/lib/R/library/tools/DESCRIPTION
./prefix_host/lib/R/library/tools/INDEX
./prefix_host/lib/R/library/tools/NAMESPACE
./prefix_host/lib/R/library/utils/Meta/Rd.rds
./prefix_host/lib/R/library/utils/Meta/features.rds
./prefix_host/lib/R/library/utils/Meta/hsearch.rds
./prefix_host/lib/R/library/utils/Meta/links.rds
./prefix_host/lib/R/library/utils/Meta/nsInfo.rds
./prefix_host/lib/R/library/utils/Meta/package.rds
./prefix_host/lib/R/library/utils/R/sysdata.rdb
./prefix_host/lib/R/library/utils/R/sysdata.rdx
./prefix_host/lib/R/library/utils/R/utils
./prefix_host/lib/R/library/utils/Sweave/Sweave-test-1.Rnw
./prefix_host/lib/R/library/utils/Sweave/example-1.Rnw
./prefix_host/lib/R/library/utils/doc/Sweave.pdf
./prefix_host/lib/R/library/utils/help/AnIndex
./prefix_host/lib/R/library/utils/help/aliases.rds
./prefix_host/lib/R/library/utils/help/paths.rds
./prefix_host/lib/R/library/utils/help/utils.rdb
./prefix_host/lib/R/library/utils/help/utils.rdx
./prefix_host/lib/R/library/utils/html/00Index.html
./prefix_host/lib/R/library/utils/html/R.css
./prefix_host/lib/R/library/utils/libs/utils.so
./prefix_host/lib/R/library/utils/misc/exDIF.csv
./prefix_host/lib/R/library/utils/misc/exDIF.dif
./prefix_host/lib/R/library/utils/DESCRIPTION
./prefix_host/lib/R/library/utils/INDEX
./prefix_host/lib/R/library/utils/NAMESPACE
./prefix_host/lib/R/library/utils/iconvlist
./prefix_host/lib/R/library/rlang/NAMESPACE
./prefix_host/lib/R/library/rlang/LICENSE
./prefix_host/lib/R/library/rlang/NEWS.md
./prefix_host/lib/R/library/rlang/DESCRIPTION
./prefix_host/lib/R/library/rlang/Meta/package.rds
./prefix_host/lib/R/library/rlang/Meta/features.rds
./prefix_host/lib/R/library/rlang/Meta/Rd.rds
./prefix_host/lib/R/library/rlang/Meta/hsearch.rds
./prefix_host/lib/R/library/rlang/Meta/links.rds
./prefix_host/lib/R/library/rlang/Meta/nsInfo.rds
./prefix_host/lib/R/library/rlang/libs/rlang.so
./prefix_host/lib/R/library/rlang/R/rlang
./prefix_host/lib/R/library/rlang/R/rlang.rdb
./prefix_host/lib/R/library/rlang/R/rlang.rdx
./prefix_host/lib/R/library/rlang/backtrace-ver
./prefix_host/lib/R/library/rlang/help/paths.rds
./prefix_host/lib/R/library/rlang/help/rlang.rdb
./prefix_host/lib/R/library/rlang/help/rlang.rdx
./prefix_host/lib/R/library/rlang/help/AnIndex
./prefix_host/lib/R/library/rlang/help/aliases.rds
./prefix_host/lib/R/library/rlang/help/figures/logo.png
./prefix_host/lib/R/library/rlang/help/figures/lifecycle-archived.svg
./prefix_host/lib/R/library/rlang/help/figures/lifecycle-defunct.svg
./prefix_host/lib/R/library/rlang/help/figures/lifecycle-deprecated.svg
./prefix_host/lib/R/library/rlang/help/figures/lifecycle-experimental.svg
./prefix_host/lib/R/library/rlang/help/figures/lifecycle-maturing.svg
./prefix_host/lib/R/library/rlang/help/figures/lifecycle-questioning.svg
./prefix_host/lib/R/library/rlang/help/figures/lifecycle-retired.svg
./prefix_host/lib/R/library/rlang/help/figures/lifecycle-soft-deprecated.svg
./prefix_host/lib/R/library/rlang/help/figures/lifecycle-stable.svg
./prefix_host/lib/R/library/rlang/help/figures/lifecycle-superseded.svg
./prefix_host/lib/R/library/rlang/html/00Index.html
./prefix_host/lib/R/library/rlang/html/R.css
./prefix_host/lib/R/library/rlang/INDEX
./prefix_host/lib/R/modules/lapack.so
./prefix_host/lib/R/share/R/REMOVE.R
./prefix_host/lib/R/share/R/examples-footer.R
./prefix_host/lib/R/share/R/examples-header.R
./prefix_host/lib/R/share/R/nspackloader.R
./prefix_host/lib/R/share/R/tests-startup.R
./prefix_host/lib/R/share/Rd/macros/system.Rd
./prefix_host/lib/R/share/dictionaries/R_Rd_files.rds
./prefix_host/lib/R/share/dictionaries/R_manuals.rds
./prefix_host/lib/R/share/dictionaries/R_vignettes.rds
./prefix_host/lib/R/share/dictionaries/en_stats.rds
./prefix_host/lib/R/share/encodings/Adobe-glyphlist
./prefix_host/lib/R/share/encodings/character-sets
./prefix_host/lib/R/share/java/README
./prefix_host/lib/R/share/java/getsp.class
./prefix_host/lib/R/share/licenses/AGPL-3
./prefix_host/lib/R/share/licenses/BSD_2_clause
./prefix_host/lib/R/share/licenses/Artistic-2.0
./prefix_host/lib/R/share/licenses/license.db
./prefix_host/lib/R/share/licenses/BSD_3_clause
./prefix_host/lib/R/share/licenses/GPL-3
./prefix_host/lib/R/share/licenses/GPL-2
./prefix_host/lib/R/share/licenses/LGPL-2
./prefix_host/lib/R/share/licenses/LGPL-2.1
./prefix_host/lib/R/share/licenses/LGPL-3
./prefix_host/lib/R/share/licenses/MIT
./prefix_host/lib/R/share/make/basepkg.mk
./prefix_host/lib/R/share/make/check_vars_ini.mk
./prefix_host/lib/R/share/make/check_vars_out.mk
./prefix_host/lib/R/share/make/clean.mk
./prefix_host/lib/R/share/make/config.mk
./prefix_host/lib/R/share/make/lazycomp.mk
./prefix_host/lib/R/share/make/shlib.mk
./prefix_host/lib/R/share/make/vars.mk
./prefix_host/lib/R/share/make/winshlib.mk
./prefix_host/lib/R/share/sh/echo.sh
./prefix_host/lib/R/share/texmf/bibtex/bib/Rnews.bib
./prefix_host/lib/R/share/texmf/bibtex/bib/RJournal.bib
./prefix_host/lib/R/share/texmf/bibtex/bst/jss.bst
./prefix_host/lib/R/share/texmf/tex/latex/Rd.sty
./prefix_host/lib/R/share/texmf/tex/latex/Sweave.sty
./prefix_host/lib/R/share/texmf/tex/latex/jss.cls
./prefix_host/lib/R/share/texmf/tex/latex/omscmtt.fd
./prefix_host/lib/R/COPYING
./prefix_host/lib/R/SVN-REVISION
./prefix_host/lib/pkgconfig/libR.pc
./prefix_host/share/man/man1/R.1
./prefix_host/share/man/man1/Rscript.1
`
